/*
 * Copyright 2023 Sony Semiconductor Solutions Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

export { BoundingBox } from './smart-camera/bounding-box';
export { BoundingBox2d } from './smart-camera/bounding-box2d';
export { GeneralObject } from './smart-camera/general-object';
export { ObjectDetectionData } from './smart-camera/object-detection-data';
export { ObjectDetectionTop } from './smart-camera/object-detection-top';
